language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: pypy3.5-5.8.0
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - python -m pip install pip -U
  - python -m pip install tox coverage coveralls
  - python -m virtualenv --version
  - python -m easy_install --version
  - python -m pip --version
  - python -m tox --version

script: make test
after_success: coveralls
branches:
  only:
    - /.*/
